### ISSUE TITLE
Failed to set up

### ISSUE THREAD

**Issue by obrien-james** [gunkutzeybek/hikaxpro_hacs#6]
Hi,

I’ve tried setting up the HACS integration, added the repository as custom repository and then followed the set up.
Set the host the the AX pro IP, user name and password. However, I get a failed to set up error.

the log reports the following stack trace:

`This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/hikvision_axpro/__init__.py:30 
Integration: hikvision_axpro 
First occurred: 08:43:14 (2 occurrences) 
Last logged: 08:43:14

Error setting up entry Hikvision_axpro_192.168.87.103 for hikvision_axpro
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hikvision_axpro/__init__.py", line 30, in async_setup_entry
    mac = await hass.async_add_executor_job(axpro.get_interface_mac_address, 1)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hikaxpro.py", line 168, in get_interface_mac_address
    response = self.makeRequest(interfacesEndpoint, consts.Method.GET)
  File "/usr/local/lib/python3.10/site-packages/hikaxpro.py", line 212, in makeRequest
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/hikaxpro.py", line 62, in connect
    encodedPassword = self.encodePassword(params)
  File "/usr/local/lib/python3.10/site-packages/hikaxpro.py", line 44, in encodePassword
    if sessionCap.isIrreversible:
AttributeError: 'NoneType' object has no attribute 'isIrreversible'
`

I’m currently using the username and password that I can use to log in via the wed interface.

**Comment by obrien-james** [comment]
I re-tried and it seems to be working. I had the same issue initially when using the HikAxPro library in a quick python script to test it.

Also I have tried using a different Hik-connect account and I can’t seem to get it to work - Is it only the admin account (not installer) that is able to connect to ISAP?

**Comment by abdel-elbel** [comment]
I also have problems setting this up, I keep getting "Invalid authentication".
Can the contributor share a small guide of how to fill the pop-up config form in Home assistant?
@obrien-james can you share the python script you used to test it?

**Comment by Bruno27610** [comment]
Hello
I'm French
Where do you write the identifiers (user, password, host) in configuration.yalm? And how ? Thank you for your answers
